# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|


  config.vm.define "okd" do |okd|
    okd.vm.box = "centos/7"
    okd.vm.hostname = "okd.example.com"
#    okd.disksize.size = '30GB'
    okd.vm.network "public_network",
      use_dhcp_assigned_default_route: true
    okd.vm.network "private_network", ip: "172.42.42.100"
    okd.vm.provider "virtualbox" do |v|
      v.name = "lemp"
      v.memory = 5120
      v.cpus = 2
    end
    okd.vm.provision "shell", path: "okd.sh"
  end
end
