# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|


  config.vm.define "lemp" do |lemp|
    lemp.vm.box = "ubuntu/bionic64"
    lemp.vm.hostname = "lemp.example.com"
#    lemp.disksize.size = '30GB'
    lemp.vm.network "public_network",
      use_dhcp_assigned_default_route: true
    lemp.vm.network "private_network", ip: "172.42.42.100"
    lemp.vm.provider "virtualbox" do |v|
      v.name = "lemp"
      v.memory = 1536
      v.cpus = 2
    end
    lemp.vm.provision "shell", path: "lemp.sh"
  end
end
